### ISSUE TITLE
fork express

### ISSUE THREAD

**Issue by wgyt** [wgytcraft/wgytcraft-hosting#15]
express has so many dependencies, we should move to using node's built in http module

**Comment by GrahamSH-LLK** [comment]
No

**Comment by GrahamSH-LLK** [comment]
Express is amazing

**Comment by wgyt** [comment]
fine....
I know express is amazing, but can't we just fork express and remove the stuff we don't need?

**Comment by retronbv** [comment]
we probably could

**Comment by retronbv** [comment]
it would take a while tho

**Comment by wgyt** [comment]
most o the app.* functions aren't used, we only use app.set, app.all and app.listen
we could probably save a lot of code by doing this
