### ISSUE TITLE
make modules not require github

### ISSUE THREAD

**Issue by wgyt** [wgytcraft/wgytcraft-hosting#6]
- [x] allow other git sources
- [x] allow local modules
local modules work, let's make this official
other git sources could be added later.
cc @retronbv

**Comment by retronbv** [comment]
We should allow gitlab and gitbucket? Those are the most used other than GitHub

**Comment by wgyt** [comment]
> We should allow gitlab and gitbucket? Those are the most used other than GitHub

true, but we can allow all git sources if we wanted to

**Comment by retronbv** [comment]
Is the node package just for GitHub or all git sources?

**Comment by wgyt** [comment]
> Is the node package just for GitHub or all git sources?

There aren't any node packages, but right now we only ***officially*** support github. Local modules work, but they aren't officially supported.

**Comment by retronbv** [comment]
> There aren't any node packages

https://github.com/wgytcraft/wgytcraft-hosting/blob/f0c07d97e1a9d80ff22bf98ec8b6990668194464/index.js#L5

**Comment by wgyt** [comment]
> > There aren't any node packages
> 
> https://github.com/wgytcraft/wgytcraft-hosting/blob/f0c07d97e1a9d80ff22bf98ec8b6990668194464/index.js#L5

ohhh thats what you were talking about, it supports all git sources, right now we set up the code to use github only, but the module can use other sources if we code it in.

**Comment by retronbv** [comment]
Yup

**Comment by wgyt** [comment]
Now that we have that sorted out, how would we import other modules from other git sources? would we make a new array in modules.json called otherGitModules and another one for local modules called localModules and import the git modules and use them the same way as github modules?

**Comment by retronbv** [comment]
we could have arrays `localModules` And `gitModules`

**Comment by wgyt** [comment]
> we could have arrays `localModules` And `gitModules`

yes, we should change the current array for github modules to be `githubModule`

**Comment by retronbv** [comment]
No, it should be able to have GitHub modules in the git modules section

**Comment by wgyt** [comment]
> No, it should be able to have GitHub modules in the git modules section

no, I disagree. github modules should be easy to import like they are now. you shouldn't need to type in github.com/wgytcraft/test.git to import something from github

**Comment by retronbv** [comment]
maybe `gh://wgytcraft/test` and it will make it`github.com/wgytcraft/test.git`

**Comment by wgyt** [comment]
> maybe `gh://wgytcraft/test` and it will make it`github.com/wgytcraft/test.git`

that is a good idea, we should also make one for gitlab and bitbucket.

**Comment by retronbv** [comment]
gl://
gb://

**Comment by wgyt** [comment]
> gl://
> gb://

nice idea, but shouldn't bitbucket be bb://

**Comment by retronbv** [comment]
I thought it was gitbucket lol

**Comment by wgyt** [comment]
we should make a fork or a new branch to make this possible,
by the way git urls should be git://

**Comment by retronbv** [comment]
is there git urls?

**Comment by wgyt** [comment]
> is there git urls?

yes, git:// would be the prefix for them all once we change the gh:// or gl:// or bb:// to the respective git:// url, if the prefix was git:// we wouldn't change anything

**Comment by retronbv** [comment]
oh yeah I’m dumb

**Comment by wgyt** [comment]
@retronbv I forked the repo, can you help with making this possible on https://github.com/world-languages/wgytcraft-hosting

**Comment by retronbv** [comment]
why is it in the world_languages org?

**Comment by wgyt** [comment]
> why is it in the world_languages org?

it was a free org 🤷🏻‍♂️

**Comment by retronbv** [comment]
> > why is it in the world_languages org?
> 
> it was a free org 🤷🏻‍♂️

Lol

**Comment by retronbv** [comment]
Completed (@wgyt I can’t close it)
